### ISSUE TITLE
About the Experimental Dataset

### ISSUE THREAD

**Issue by nldyy** [pdclab/peregrine#18]
Thank you for your previous answer to the matching order question. Now I have a new problem, I initially only run the code with the citeseer dataset, now I want to run the code with other datasets mentioned in the paper, from https://github.com/pdclab/peregrine/blob The data set downloaded from /master/experiments-guide.md, I can't run it successfully. I added a statement to output the number of vertices and edges in the data DataGraph function. When clion runs with the mico data set, the feedback I get is
![image](https://user-images.githubusercontent.com/38241803/225253956-bf6d3699-d6a0-4b9a-8d10-bce6122edd43.png)
the number of vertices and edges is not consistent with my known mico data set, and the same is true for other data sets。
The feedback obtained on the command line is ”Segmentation fault (core dumped)“
Have you encountered any related problems?Do you have any relevant solutions?

**Comment by kjamsh** [comment]
Hi,

The data file format has changed since the EuroSys 2020 submission. The datasets in `experiments-guide.md` only work with the Peregrine code provided in the old `eurosys20-experiments` branch (which I do not recommend using beyond trying to recreate the original paper's results).

The original MiCo graph can be obtained [here](https://github.com/ehab-abdelhamid/GraMi/) (you'll have to convert it to Peregrine format following instructions in the README).
