### ISSUE TITLE
Extending Multi Label Functionality

### ISSUE THREAD

**Issue by wilheimX** [pdclab/peregrine#22]
Hi,

I have been playing around with the software and I really like it. I am wondering if it is possible for me to extend the software to handle multi labels on vertices? Right now it can only support 1 label per vertex. If so, how should I proceed in doing this?

**Comment by kjamsh** [comment]
Hello,

I appreciate your interest! Peregrine's design can support multiple labels on vertices, but it requires significant changes across the codebase that I do not have time to guide you in making. At a high level, the data graph, pattern analysis, and pattern matching code would all have to be adjusted to account for multiple labels instead of just one. Best of luck!
