### ISSUE TITLE
Wrong output and different results using the data converter

### ISSUE THREAD

**Issue by lady-bluecopper** [pdclab/peregrine#8]
Hello there,
I had some issues while testing your framework, and I hope you can help me understand what is wrong.

The edges of my graph are:

  0 1
  1 2
  2 3
  4 5
  5 6
  6 7
  8 9
  9 10
  10 11

and the node labels are:

  0 1
  1 1
  2 1
  3 1
  4 1
  5 2
  6 2
  7 1
  8 1
  9 2
  10 1
  11 2

**FIRST ISSUE** 
I used your data converter _convert_data_ on a Mac and on a Ubuntu PC, obtaining different results. On the Ubuntu PC, the datagraph has the correct number of nodes and edges, while on the Mac, it has 11 nodes and 8 edges. 
Could you help me understand what could be the reason?

**SECOND ISSUE**
Then, I run the _fsm_ algorithm using _size = 1_ and _support = 4_:

        bin/fsm data/graph 1 4 5

and obtained the output:

	1-FSM with threshold 4
	Finished reading datagraph: |V| = 12 |E| = 9
	-------
	all patterns finished after 0.000489s
	0 frequent patterns: 

However, the edge with node labels equal to 1 has MNI support equal to 4, because the matches for the first vertex are {0,1,2,3} and the matches for the second vertex are {0,1,2,3}, and hence the min is 4.
I do not understand why my output does not contain any pattern.

**THIRD ISSUE**
Finally, I tried to set the frequency to 0, to generate all the possible patterns of a given size:

        bin/fsm data/graph 3 0 5

My output contains patterns like the following one:

        [1,2-2,1][1,2-3,1][1,2-4,0]: 0

Given that the nodes in the input graph have label equal to either 1 or 2, why are there patterns with node label equal to 0?

**Comment by kjamsh** [comment]
Hi Giulia,

I pushed changes to address your last two issues. They were trivial oversights on my part:

Second issue: the sample FSM app starts from two edges. I've updated it to start from 1 edge since that's more general.
Third issue: when support is 0 sometimes the system printed spurious patterns with support 0 in addition to the patterns it matched. This is no longer the case.

Thanks for bringing those up, it helps make Peregrine better :)

The first issue is the harder one to deal with since I don't have easy access to a Mac. My guess is some subtle difference in the file I/O system calls between Linux and Mac is causing Peregrine to skip an edge when reading or writing. I might be able help if you attach the `data.bin` file generated on the Mac, but I'm afraid I can't promise full support for Macs right now.

Let me know if you run into any other problems!

**Comment by lady-bluecopper** [comment]
Hello,
thanks for your help!
Now issue 2 is solved.
However, I still get spurious patterns containing label 0. I wonder what would happen if my input nodes have label 0 and 1. Which label would these spurious patterns contain?

**Comment by kjamsh** [comment]
Sorry about that, one last change was missing. 

Though the point is moot now, in fact you wouldn't get spurious patterns if you had label 0 in your dataset.

Anything else I can help you with?

**Comment by lady-bluecopper** [comment]
Perfect! Thanks again!
